8.1.5
июн 14, 2015 11:31:34 PM
org.hibernate.annotations.common.reflection.java.JavaReflectionManager
<clinit>
INFO: HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
июн 14, 2015 11:31:34 PM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate Core {4.3.10.Final}
июн 14, 2015 11:31:34 PM org.hibernate.cfg.Environment <clinit>
INFO: HHH000206: hibernate.properties not found
июн 14, 2015 11:31:34 PM org.hibernate.cfg.Environment
buildBytecodeProvider
INFO: HHH000021: Bytecode provider name : javassist
июн 14, 2015 11:31:34 PM org.hibernate.cfg.Configuration configure
INFO: HHH000043: Configuring from resource: /hibernate.cfg.xml
июн 14, 2015 11:31:34 PM org.hibernate.cfg.Configuration
getConfigurationInputStream
INFO: HHH000040: Configuration resource: /hibernate.cfg.xml
июн 14, 2015 11:31:34 PM
org.hibernate.internal.util.xml.DTDEntityResolver resolveEntity
WARN: HHH000223: Recognized obsolete hibernate namespace
http://hibernate.sourceforge.net/. Use namespace
http://www.hibernate.org/dtd/ instead. Refer to Hibernate 3.6 Migration
Guide!
июн 14, 2015 11:31:34 PM org.hibernate.cfg.Configuration addResource
INFO: HHH000221: Reading mappings from resource: GroupData.hbm.xml
июн 14, 2015 11:31:34 PM
org.hibernate.internal.util.xml.DTDEntityResolver resolveEntity
WARN: HHH000223: Recognized obsolete hibernate namespace
http://hibernate.sourceforge.net/. Use namespace
http://www.hibernate.org/dtd/ instead. Refer to Hibernate 3.6 Migration
Guide!
июн 14, 2015 11:31:34 PM org.hibernate.cfg.Configuration doConfigure
INFO: HHH000041: Configured SessionFactory: null
июн 14, 2015 11:31:34 PM
org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl
configure
WARN: HHH000402: Using Hibernate built-in connection pool (not for
production use!)
июн 14, 2015 11:31:34 PM
org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl
buildCreator
INFO: HHH000401: using driver [com.mysql.jdbc.Driver] at URL
[jdbc:mysql://localhost:3306/addressbook]
июн 14, 2015 11:31:34 PM
org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl
buildCreator
INFO: HHH000046: Connection properties: {user=root, password=****}
июн 14, 2015 11:31:34 PM
org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl
buildCreator
INFO: HHH000006: Autocommit mode: false
июн 14, 2015 11:31:34 PM
org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl
configure
INFO: HHH000115: Hibernate connection pool size: 20 (min=1)
июн 14, 2015 11:31:35 PM org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
Initial SessionFactory creation
failed.org.hibernate.InvalidMappingException: Could not parse mapping
document from resource GroupData.hbm.xml
Exception in thread "main" java.lang.ExceptionInInitializerError
at
com.example.fw.HibernateUtil.buildSessionFactory(HibernateUtil.java:18)
at com.example.fw.HibernateUtil.<clinit>(HibernateUtil.java:8)
at com.example.fw.HibernateHelper.listGroups(HibernateHelper.java:18)
at com.example.tests.Sample.main(Sample.java:19)
Caused by: org.hibernate.InvalidMappingException: Could not parse
mapping document from resource GroupData.hbm.xml
at
org.hibernate.cfg.Configuration$MetadataSourceQueue.processHbmXml(Configuration.java:3819)
at
org.hibernate.cfg.Configuration$MetadataSourceQueue.processHbmXmlQueue(Configuration.java:3808)
at
org.hibernate.cfg.Configuration$MetadataSourceQueue.processMetadata(Configuration.java:3796)
at
org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1412)
at
org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1846)
at
org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1930)
at
com.example.fw.HibernateUtil.buildSessionFactory(HibernateUtil.java:13)
... 3 more
Caused by: org.hibernate.MappingException: class
org.example.framework.GroupData not found while looking for property: id
at
org.hibernate.internal.util.ReflectHelper.reflectedPropertyClass(ReflectHelper.java:233)
at
org.hibernate.mapping.SimpleValue.setTypeUsingReflection(SimpleValue.java:375)
at org.hibernate.cfg.HbmBinder.bindSimpleId(HbmBinder.java:454)
at
org.hibernate.cfg.HbmBinder.bindRootPersistentClassCommonValues(HbmBinder.java:387)
at org.hibernate.cfg.HbmBinder.bindRootClass(HbmBinder.java:327)
at org.hibernate.cfg.HbmBinder.bindRoot(HbmBinder.java:178)
at
org.hibernate.cfg.Configuration$MetadataSourceQueue.processHbmXml(Configuration.java:3816)
... 9 more
Caused by: java.lang.ClassNotFoundException:
org.example.framework.GroupData
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at
org.hibernate.internal.util.ReflectHelper.classForName(ReflectHelper.java:193)
at
org.hibernate.internal.util.ReflectHelper.reflectedPropertyClass(ReflectHelper.java:229)
... 15 more